In [15]:
import pandas as pd

In [16]:
teams = pd.read_csv('teams.csv')
matches = pd.read_csv('2025_match_results.csv')
players = pd.read_csv('2025_player_stats.csv')
standings = pd.read_csv('big5_standings.csv')

In [17]:
position = pd.merge(standings, teams, how="left", left_on="team", right_on="api-football_name")
record = pd.merge(matches, teams, how="left", left_on="Team", right_on="worldfootballR_name")
common_players = pd.merge(players, teams, how="left", left_on="Squad", right_on="worldfootballR_name")

In [18]:
x = "Wolves"

First the league positions of x over the years

In [19]:
x_position = position[position['full_name'] == x]
x_position[['season', 'position']]

    season  position
12    2022        13
33    2023        14
55    2024        16

Then how many wins draws and losses last season.

In [20]:
wins = record[(record['full_name'] == x) & (record['Result'] == "W")]
len(wins)

12

In [21]:
draws = record[(record['full_name'] == x) & (record['Result'] == "D")]
len(draws)

6

In [22]:
losses = record[(record['full_name'] == x) & (record['Result'] == "L")]
len(losses)

20

Biggest win and loss

In [23]:
big_loss = record[record['full_name'] == x].sort_values(by='Diff', ascending=True).head(1)
print(f"The team's biggest loss was to {big_loss['Opp'].to_string(index=False)}, losing by {big_loss['Diff'].to_string(index=False)} goals.")

The team's biggest loss was to Chelsea, losing by -4 goals.

In [24]:
big_win = record[record['full_name'] == x].sort_values(by='Diff', ascending=False).head(1)
print(f"The team's biggest win was to {big_win['Opp'].to_string(index=False)}, winning by {big_win['Diff'].to_string(index=False)} goals.")

The team's biggest win was to Fulham, winning by 3 goals.

Most common XI:

In [25]:
x_common = common_players[common_players['full_name'] == x].sort_values(by='MP_Playing Time', ascending=False).head(11)
x_common[['Player', 'Pos', 'MP_Playing Time']]

                     Player    Pos  MP_Playing Time
8           Rayan Aït-Nouri     DF               37
203              João Gomes     MF               36
51   Jean-Ricner Bellegarde  MF,FW               35
493    Jørgen Strand Larsen     FW               35
464           Nélson Semedo     DF               34
26                    André     MF               33
115           Matheus Cunha  MF,FW               33
205              Toti Gomes     DF               31
141            Matt Doherty     DF               30
216          Gonçalo Guedes  MF,FW               29
446                 José Sá     GK               29